name = "ArraysOfArrays"
uuid = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
version = "0.4.1"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[compat]
julia = "1"
UnsafeArrays = ">= 0.2.0"

[extras]
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ElasticArrays", "StaticArrays", "StatsBase", "Test"]
